version: '3.8'
services:
  fuse-agent:
    image: ${DOCKERHUB_USERNAME}/fuse-agent:${DOCKER_IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge